version: '{branch}.{build}'
image: Visual Studio 2022
branches:
  except:
    - gh-pages
skip_commits:
  files:
    - .github/workflows/*
    - .github/actions/*
# clone_depth: 1 produces odd "fatal: reference is not a tree" if pushing during checkout
clone_depth: 5
environment:
  matrix:
    - TOXENV: lint
      PYTHON: "C:\\Python38-x64"
    - TOXENV: docs-lint
      PYTHON: "C:\\Python38-x64"
    - TOXENV: pycodestyle
      PYTHON: "C:\\Python312-x64"
    - TOXENV: pycodestyle
      PYTHON: "C:\\Python38-x64"
    - TOXENV: WSL
      PYTHON: ''
    # Windows cannot even import the module when they unconditionally import, see below.
    #- TOXENV: run-module
    #  PYTHON: "C:\\Python38-x64"
    #- TOXENV: run-entrypoint
    #  PYTHON: "C:\\Python38-x64"
    # Windows is not ready for testing!!!
    # Python's non-blocking pipes, grp, pwd, os.geteuid(), and socket.AF_UNIX are all Unix-only.
    # Python's fcntl, grp, pwd, os.geteuid(), and socket.AF_UNIX are all Unix-only.
    #- TOXENV: py37
    #  PYTHON: "C:\\Python37-x64"
    #- TOXENV: py38
    #  PYTHON: "C:\\Python38-x64"
    #- TOXENV: py39
    #  PYTHON: "C:\\Python39-x64"
    #- TOXENV: py310
    #  PYTHON: "C:\\Python39-x64"
    #- TOXENV: py311
    #  PYTHON: "C:\\Python39-x64"
    #- TOXENV: py312
    #  PYTHON: "C:\\Python39-x64"
matrix:
  allow_failures:
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
init:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
for:
  - matrix:
      except:
       - TOXENV: WSL
    install:
      - pip install tox
    test_script:
      - tox
  - matrix:
      only:
       - TOXENV: WSL
    # run the wsl -l call last for better error on failure
    install:
     - wsl pwd
     - wsl whoami
     - wsl.exe -l || ver>nul
     - wsl cat /etc/os-release
     - wsl sudo DEBIAN_FRONTEND=noninteractive apt-get update
     - wsl sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y python3-venv python3-pip
     - wsl python3 -m venv .
     - wsl bin/pip install -U pip tox
    test_script:
      - wsl bin/tox
build: false
cache:
  # Not including the .tox directory since it takes longer to download/extract
  # the cache archive than for tox to clean install from the pip cache.
  - '%LOCALAPPDATA%\pip\Cache -> tox.ini'
notifications:
  - provider: Email
    on_build_success: false
    on_build_status_changed: false
